db:
  username: ${username.value:postgres}
  password: 12345678
  driver: PostgresDriver
  url: postgres:5432
  hosts: localhost,127.0.0.1
  properties:
    first: 1
    second: 2
    third.value: 3
  pool:
    size: 12
    timeout: 10
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3

logging:
  level:
    root: INFO
    ru.ru.clevertec.dal.pool: INFO
  file:
    name: paramonov.log
    path: /
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate

